let arr=[
    {
        name:"aman",
        age:16,
        course:"btech"
    },
    {
        name:"sahil",
        age:16,
        course:"btech"
    },
    {
        name:"Rohan",
        age:16,
        course:"btech"
    },
    {
        name:"manish",
        age:16,
        course:"btech"
    },
    {
        name:"sakshi",
        age:16,
        course:"btech"
    }
]
arr.map((items,i)=>{
    console.log(`hello i am ${items.name} form ${items.course} department`)
})
